### ISSUE TITLE
Question on the usage.

### ISSUE THREAD

**Issue by dukechain2333** [Michaelzhouisnotwhite/save-pic-from-clipboard#1]
Can you tell me when you exactly going to use this tool since we can already check the clip board on both Windows and MacOS?

Maybe on linux? But I suppose there are some of the desktop environments already support that (for example, KDE plasma has a tool called Klipper).

**Comment by Michaelzhouisnotwhite** [comment]
Thx for your feedback! Although there is tools that can user check the clipboard and paste it wherever you want, you can not save the figure to your explorer as a ".png"  or ".jpeg" file.

**Comment by Michaelzhouisnotwhite** [comment]
> Can you tell me when you exactly going to use this tool since we can already check the clip board on both Windows and MacOS?
> 
> Maybe on linux? But I suppose there are some of the desktop environments already support that (for example, KDE plasma has a tool called Klipper).

AND!! Why my wife is your Profile Photo 🤔  :  )
